--- #YAML:1.0
name:               PICA-Record
version:            0.56
abstract:           Perl extension for handling PICA+ records
author:
    - Jakob Voss <jakob.voss@gbv.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Simple:      4.58
    DBD::SQLite:         1.23
    DBI:                 1.0
    Encode:              2.33
    IO::File:            1.11
    IO::Scalar:          1.126
    LWP::Simple:         1.0
    PerlIO:              1.0
    Scalar::Util:        1.14
    SOAP::Lite:          0.71
    String::Escape:      0
    Unicode::Normalize:  0.23
    URI::Escape:         1.35
    XML::Parser:         2.32
    XML::Writer:         0.605
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
