# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PICA-Record
version:      0.39
version_from: lib/PICA/Record.pm
installdirs:  site
requires:
    Carp:                          0
    LWP::UserAgent:                0
    SOAP::Lite:                    0
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
