---
abstract: 'Perl extension for handling PICA+ records'
author:
  - 'Jakob Voss <jakob.voss@gbv.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PICA-Record
no_index:
  directory:
    - t
    - inc
requires:
  Config::Simple: 4.58
  DBD::SQLite: 1.23
  DBI: 1.0
  Encode: 2.33
  IO::File: 1.11
  IO::Scalar: 1.126
  LWP::Simple: 1.0
  PerlIO: 1.0
  SOAP::Lite: 0.71
  Scalar::Util: 1.14
  String::Escape: 0
  URI::Escape: 1.35
  Unicode::Normalize: 0.23
  XML::SAX: 0.96
  XML::Writer: 0.605
version: 0.582
