#!/usr/bin/perl

=head1 NAME

picawebcat

=head1 DESCRIPTION

This script is deprecated. Please use 'picaimport' instead.

=cut

print "This script is deprecated. Please use 'picaimport' instead!\n";
